<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

/**
 * Opens registration to every recognized country. Canada and the United
 * States get real state/province dropdowns on the registration form
 * (see ProvinceCodes/StateCodes + register-form.blade.php) — every other
 * country here falls back to the existing free-text region field, and
 * none of them are charged platform tax (PlatformTaxCalculator is gated
 * to Canada only), so activating this full list has no billing effect.
 *
 * Uses updateOrCreate on short_code so re-running this seeder is safe
 * and won't duplicate the handful of countries added by hand already.
 */
class CountrySeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->countries() as $country) {
            Country::updateOrCreate(
                ['short_code' => $country['short_code']],
                [
                    'name' => $country['name'],
                    'currency_code' => $country['currency_code'],
                    'currency_symbol' => $country['currency_symbol'],
                    'currency_position' => $country['currency_position'],
                    'is_active' => true,
                ]
            );
        }
    }

    /**
     * @return array<int, array{name: string, short_code: string, currency_code: string, currency_symbol: string, currency_position: string}>
     */
    private function countries(): array
    {
        $b = 'before';
        $a = 'after';

        return [
            ['name' => 'Afghanistan', 'short_code' => 'AF', 'currency_code' => 'AFN', 'currency_symbol' => '؋', 'currency_position' => $a],
            ['name' => 'Albania', 'short_code' => 'AL', 'currency_code' => 'ALL', 'currency_symbol' => 'L', 'currency_position' => $a],
            ['name' => 'Algeria', 'short_code' => 'DZ', 'currency_code' => 'DZD', 'currency_symbol' => 'د.ج', 'currency_position' => $a],
            ['name' => 'Andorra', 'short_code' => 'AD', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Angola', 'short_code' => 'AO', 'currency_code' => 'AOA', 'currency_symbol' => 'Kz', 'currency_position' => $a],
            ['name' => 'Antigua and Barbuda', 'short_code' => 'AG', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Argentina', 'short_code' => 'AR', 'currency_code' => 'ARS', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Armenia', 'short_code' => 'AM', 'currency_code' => 'AMD', 'currency_symbol' => '֏', 'currency_position' => $a],
            ['name' => 'Australia', 'short_code' => 'AU', 'currency_code' => 'AUD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Austria', 'short_code' => 'AT', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Azerbaijan', 'short_code' => 'AZ', 'currency_code' => 'AZN', 'currency_symbol' => '₼', 'currency_position' => $a],
            ['name' => 'Bahamas', 'short_code' => 'BS', 'currency_code' => 'BSD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Bahrain', 'short_code' => 'BH', 'currency_code' => 'BHD', 'currency_symbol' => '.د.ب', 'currency_position' => $a],
            ['name' => 'Bangladesh', 'short_code' => 'BD', 'currency_code' => 'BDT', 'currency_symbol' => '৳', 'currency_position' => $b],
            ['name' => 'Barbados', 'short_code' => 'BB', 'currency_code' => 'BBD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Belarus', 'short_code' => 'BY', 'currency_code' => 'BYN', 'currency_symbol' => 'Br', 'currency_position' => $a],
            ['name' => 'Belgium', 'short_code' => 'BE', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Belize', 'short_code' => 'BZ', 'currency_code' => 'BZD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Benin', 'short_code' => 'BJ', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'currency_position' => $a],
            ['name' => 'Bhutan', 'short_code' => 'BT', 'currency_code' => 'BTN', 'currency_symbol' => 'Nu.', 'currency_position' => $b],
            ['name' => 'Bolivia', 'short_code' => 'BO', 'currency_code' => 'BOB', 'currency_symbol' => 'Bs.', 'currency_position' => $b],
            ['name' => 'Bosnia and Herzegovina', 'short_code' => 'BA', 'currency_code' => 'BAM', 'currency_symbol' => 'KM', 'currency_position' => $a],
            ['name' => 'Botswana', 'short_code' => 'BW', 'currency_code' => 'BWP', 'currency_symbol' => 'P', 'currency_position' => $b],
            ['name' => 'Brazil', 'short_code' => 'BR', 'currency_code' => 'BRL', 'currency_symbol' => 'R$', 'currency_position' => $b],
            ['name' => 'Brunei', 'short_code' => 'BN', 'currency_code' => 'BND', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Bulgaria', 'short_code' => 'BG', 'currency_code' => 'BGN', 'currency_symbol' => 'лв', 'currency_position' => $a],
            ['name' => 'Burkina Faso', 'short_code' => 'BF', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'currency_position' => $a],
            ['name' => 'Burundi', 'short_code' => 'BI', 'currency_code' => 'BIF', 'currency_symbol' => 'FBu', 'currency_position' => $a],
            ['name' => 'Cambodia', 'short_code' => 'KH', 'currency_code' => 'KHR', 'currency_symbol' => '៛', 'currency_position' => $a],
            ['name' => 'Cameroon', 'short_code' => 'CM', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'currency_position' => $a],
            ['name' => 'Canada', 'short_code' => 'CA', 'currency_code' => 'CAD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Cabo Verde', 'short_code' => 'CV', 'currency_code' => 'CVE', 'currency_symbol' => '$', 'currency_position' => $a],
            ['name' => 'Central African Republic', 'short_code' => 'CF', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'currency_position' => $a],
            ['name' => 'Chad', 'short_code' => 'TD', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'currency_position' => $a],
            ['name' => 'Chile', 'short_code' => 'CL', 'currency_code' => 'CLP', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'China', 'short_code' => 'CN', 'currency_code' => 'CNY', 'currency_symbol' => '¥', 'currency_position' => $b],
            ['name' => 'Colombia', 'short_code' => 'CO', 'currency_code' => 'COP', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Comoros', 'short_code' => 'KM', 'currency_code' => 'KMF', 'currency_symbol' => 'CF', 'currency_position' => $a],
            ['name' => 'Congo (Republic)', 'short_code' => 'CG', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'currency_position' => $a],
            ['name' => 'Congo (DRC)', 'short_code' => 'CD', 'currency_code' => 'CDF', 'currency_symbol' => 'FC', 'currency_position' => $a],
            ['name' => 'Costa Rica', 'short_code' => 'CR', 'currency_code' => 'CRC', 'currency_symbol' => '₡', 'currency_position' => $b],
            ['name' => "Cote d'Ivoire", 'short_code' => 'CI', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'currency_position' => $a],
            ['name' => 'Croatia', 'short_code' => 'HR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Cuba', 'short_code' => 'CU', 'currency_code' => 'CUP', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Cyprus', 'short_code' => 'CY', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Czech Republic', 'short_code' => 'CZ', 'currency_code' => 'CZK', 'currency_symbol' => 'Kč', 'currency_position' => $a],
            ['name' => 'Denmark', 'short_code' => 'DK', 'currency_code' => 'DKK', 'currency_symbol' => 'kr', 'currency_position' => $a],
            ['name' => 'Djibouti', 'short_code' => 'DJ', 'currency_code' => 'DJF', 'currency_symbol' => 'Fdj', 'currency_position' => $a],
            ['name' => 'Dominica', 'short_code' => 'DM', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Dominican Republic', 'short_code' => 'DO', 'currency_code' => 'DOP', 'currency_symbol' => 'RD$', 'currency_position' => $b],
            ['name' => 'Ecuador', 'short_code' => 'EC', 'currency_code' => 'USD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Egypt', 'short_code' => 'EG', 'currency_code' => 'EGP', 'currency_symbol' => 'E£', 'currency_position' => $b],
            ['name' => 'El Salvador', 'short_code' => 'SV', 'currency_code' => 'USD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Equatorial Guinea', 'short_code' => 'GQ', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'currency_position' => $a],
            ['name' => 'Eritrea', 'short_code' => 'ER', 'currency_code' => 'ERN', 'currency_symbol' => 'Nfk', 'currency_position' => $a],
            ['name' => 'Estonia', 'short_code' => 'EE', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Eswatini', 'short_code' => 'SZ', 'currency_code' => 'SZL', 'currency_symbol' => 'L', 'currency_position' => $b],
            ['name' => 'Ethiopia', 'short_code' => 'ET', 'currency_code' => 'ETB', 'currency_symbol' => 'Br', 'currency_position' => $a],
            ['name' => 'Fiji', 'short_code' => 'FJ', 'currency_code' => 'FJD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Finland', 'short_code' => 'FI', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'France', 'short_code' => 'FR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Gabon', 'short_code' => 'GA', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'currency_position' => $a],
            ['name' => 'Gambia', 'short_code' => 'GM', 'currency_code' => 'GMD', 'currency_symbol' => 'D', 'currency_position' => $b],
            ['name' => 'Georgia', 'short_code' => 'GE', 'currency_code' => 'GEL', 'currency_symbol' => '₾', 'currency_position' => $a],
            ['name' => 'Germany', 'short_code' => 'DE', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Ghana', 'short_code' => 'GH', 'currency_code' => 'GHS', 'currency_symbol' => '₵', 'currency_position' => $b],
            ['name' => 'Greece', 'short_code' => 'GR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Grenada', 'short_code' => 'GD', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Guatemala', 'short_code' => 'GT', 'currency_code' => 'GTQ', 'currency_symbol' => 'Q', 'currency_position' => $b],
            ['name' => 'Guinea', 'short_code' => 'GN', 'currency_code' => 'GNF', 'currency_symbol' => 'FG', 'currency_position' => $a],
            ['name' => 'Guinea-Bissau', 'short_code' => 'GW', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'currency_position' => $a],
            ['name' => 'Guyana', 'short_code' => 'GY', 'currency_code' => 'GYD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Haiti', 'short_code' => 'HT', 'currency_code' => 'HTG', 'currency_symbol' => 'G', 'currency_position' => $a],
            ['name' => 'Honduras', 'short_code' => 'HN', 'currency_code' => 'HNL', 'currency_symbol' => 'L', 'currency_position' => $b],
            ['name' => 'Hungary', 'short_code' => 'HU', 'currency_code' => 'HUF', 'currency_symbol' => 'Ft', 'currency_position' => $a],
            ['name' => 'Iceland', 'short_code' => 'IS', 'currency_code' => 'ISK', 'currency_symbol' => 'kr', 'currency_position' => $a],
            ['name' => 'India', 'short_code' => 'IN', 'currency_code' => 'INR', 'currency_symbol' => '₹', 'currency_position' => $b],
            ['name' => 'Indonesia', 'short_code' => 'ID', 'currency_code' => 'IDR', 'currency_symbol' => 'Rp', 'currency_position' => $b],
            ['name' => 'Iran', 'short_code' => 'IR', 'currency_code' => 'IRR', 'currency_symbol' => '﷼', 'currency_position' => $a],
            ['name' => 'Iraq', 'short_code' => 'IQ', 'currency_code' => 'IQD', 'currency_symbol' => 'ع.د', 'currency_position' => $a],
            ['name' => 'Ireland', 'short_code' => 'IE', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Israel', 'short_code' => 'IL', 'currency_code' => 'ILS', 'currency_symbol' => '₪', 'currency_position' => $b],
            ['name' => 'Italy', 'short_code' => 'IT', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Jamaica', 'short_code' => 'JM', 'currency_code' => 'JMD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Japan', 'short_code' => 'JP', 'currency_code' => 'JPY', 'currency_symbol' => '¥', 'currency_position' => $b],
            ['name' => 'Jordan', 'short_code' => 'JO', 'currency_code' => 'JOD', 'currency_symbol' => 'د.ا', 'currency_position' => $a],
            ['name' => 'Kazakhstan', 'short_code' => 'KZ', 'currency_code' => 'KZT', 'currency_symbol' => '₸', 'currency_position' => $a],
            ['name' => 'Kenya', 'short_code' => 'KE', 'currency_code' => 'KES', 'currency_symbol' => 'KSh', 'currency_position' => $b],
            ['name' => 'Kiribati', 'short_code' => 'KI', 'currency_code' => 'AUD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Kuwait', 'short_code' => 'KW', 'currency_code' => 'KWD', 'currency_symbol' => 'د.ك', 'currency_position' => $a],
            ['name' => 'Kyrgyzstan', 'short_code' => 'KG', 'currency_code' => 'KGS', 'currency_symbol' => 'с', 'currency_position' => $a],
            ['name' => 'Laos', 'short_code' => 'LA', 'currency_code' => 'LAK', 'currency_symbol' => '₭', 'currency_position' => $a],
            ['name' => 'Latvia', 'short_code' => 'LV', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Lebanon', 'short_code' => 'LB', 'currency_code' => 'LBP', 'currency_symbol' => 'ل.ل', 'currency_position' => $a],
            ['name' => 'Lesotho', 'short_code' => 'LS', 'currency_code' => 'LSL', 'currency_symbol' => 'L', 'currency_position' => $b],
            ['name' => 'Liberia', 'short_code' => 'LR', 'currency_code' => 'LRD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Libya', 'short_code' => 'LY', 'currency_code' => 'LYD', 'currency_symbol' => 'ل.د', 'currency_position' => $a],
            ['name' => 'Liechtenstein', 'short_code' => 'LI', 'currency_code' => 'CHF', 'currency_symbol' => 'CHF', 'currency_position' => $a],
            ['name' => 'Lithuania', 'short_code' => 'LT', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Luxembourg', 'short_code' => 'LU', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Madagascar', 'short_code' => 'MG', 'currency_code' => 'MGA', 'currency_symbol' => 'Ar', 'currency_position' => $a],
            ['name' => 'Malawi', 'short_code' => 'MW', 'currency_code' => 'MWK', 'currency_symbol' => 'MK', 'currency_position' => $a],
            ['name' => 'Malaysia', 'short_code' => 'MY', 'currency_code' => 'MYR', 'currency_symbol' => 'RM', 'currency_position' => $b],
            ['name' => 'Maldives', 'short_code' => 'MV', 'currency_code' => 'MVR', 'currency_symbol' => 'Rf', 'currency_position' => $a],
            ['name' => 'Mali', 'short_code' => 'ML', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'currency_position' => $a],
            ['name' => 'Malta', 'short_code' => 'MT', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Marshall Islands', 'short_code' => 'MH', 'currency_code' => 'USD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Mauritania', 'short_code' => 'MR', 'currency_code' => 'MRU', 'currency_symbol' => 'UM', 'currency_position' => $a],
            ['name' => 'Mauritius', 'short_code' => 'MU', 'currency_code' => 'MUR', 'currency_symbol' => '₨', 'currency_position' => $b],
            ['name' => 'Mexico', 'short_code' => 'MX', 'currency_code' => 'MXN', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Micronesia', 'short_code' => 'FM', 'currency_code' => 'USD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Moldova', 'short_code' => 'MD', 'currency_code' => 'MDL', 'currency_symbol' => 'L', 'currency_position' => $a],
            ['name' => 'Monaco', 'short_code' => 'MC', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Mongolia', 'short_code' => 'MN', 'currency_code' => 'MNT', 'currency_symbol' => '₮', 'currency_position' => $a],
            ['name' => 'Montenegro', 'short_code' => 'ME', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Morocco', 'short_code' => 'MA', 'currency_code' => 'MAD', 'currency_symbol' => 'د.م.', 'currency_position' => $a],
            ['name' => 'Mozambique', 'short_code' => 'MZ', 'currency_code' => 'MZN', 'currency_symbol' => 'MT', 'currency_position' => $a],
            ['name' => 'Myanmar', 'short_code' => 'MM', 'currency_code' => 'MMK', 'currency_symbol' => 'K', 'currency_position' => $a],
            ['name' => 'Namibia', 'short_code' => 'NA', 'currency_code' => 'NAD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Nauru', 'short_code' => 'NR', 'currency_code' => 'AUD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Nepal', 'short_code' => 'NP', 'currency_code' => 'NPR', 'currency_symbol' => '₨', 'currency_position' => $b],
            ['name' => 'Netherlands', 'short_code' => 'NL', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'New Zealand', 'short_code' => 'NZ', 'currency_code' => 'NZD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Nicaragua', 'short_code' => 'NI', 'currency_code' => 'NIO', 'currency_symbol' => 'C$', 'currency_position' => $b],
            ['name' => 'Niger', 'short_code' => 'NE', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'currency_position' => $a],
            ['name' => 'Nigeria', 'short_code' => 'NG', 'currency_code' => 'NGN', 'currency_symbol' => '₦', 'currency_position' => $b],
            ['name' => 'North Korea', 'short_code' => 'KP', 'currency_code' => 'KPW', 'currency_symbol' => '₩', 'currency_position' => $b],
            ['name' => 'North Macedonia', 'short_code' => 'MK', 'currency_code' => 'MKD', 'currency_symbol' => 'ден', 'currency_position' => $a],
            ['name' => 'Norway', 'short_code' => 'NO', 'currency_code' => 'NOK', 'currency_symbol' => 'kr', 'currency_position' => $a],
            ['name' => 'Oman', 'short_code' => 'OM', 'currency_code' => 'OMR', 'currency_symbol' => 'ر.ع.', 'currency_position' => $a],
            ['name' => 'Pakistan', 'short_code' => 'PK', 'currency_code' => 'PKR', 'currency_symbol' => '₨', 'currency_position' => $b],
            ['name' => 'Palau', 'short_code' => 'PW', 'currency_code' => 'USD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Palestine', 'short_code' => 'PS', 'currency_code' => 'ILS', 'currency_symbol' => '₪', 'currency_position' => $b],
            ['name' => 'Panama', 'short_code' => 'PA', 'currency_code' => 'PAB', 'currency_symbol' => 'B/.', 'currency_position' => $b],
            ['name' => 'Papua New Guinea', 'short_code' => 'PG', 'currency_code' => 'PGK', 'currency_symbol' => 'K', 'currency_position' => $b],
            ['name' => 'Paraguay', 'short_code' => 'PY', 'currency_code' => 'PYG', 'currency_symbol' => '₲', 'currency_position' => $b],
            ['name' => 'Peru', 'short_code' => 'PE', 'currency_code' => 'PEN', 'currency_symbol' => 'S/', 'currency_position' => $b],
            ['name' => 'Philippines', 'short_code' => 'PH', 'currency_code' => 'PHP', 'currency_symbol' => '₱', 'currency_position' => $b],
            ['name' => 'Poland', 'short_code' => 'PL', 'currency_code' => 'PLN', 'currency_symbol' => 'zł', 'currency_position' => $a],
            ['name' => 'Portugal', 'short_code' => 'PT', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Qatar', 'short_code' => 'QA', 'currency_code' => 'QAR', 'currency_symbol' => 'ر.ق', 'currency_position' => $a],
            ['name' => 'Romania', 'short_code' => 'RO', 'currency_code' => 'RON', 'currency_symbol' => 'lei', 'currency_position' => $a],
            ['name' => 'Russia', 'short_code' => 'RU', 'currency_code' => 'RUB', 'currency_symbol' => '₽', 'currency_position' => $a],
            ['name' => 'Rwanda', 'short_code' => 'RW', 'currency_code' => 'RWF', 'currency_symbol' => 'FRw', 'currency_position' => $a],
            ['name' => 'Saint Kitts and Nevis', 'short_code' => 'KN', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Saint Lucia', 'short_code' => 'LC', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Saint Vincent and the Grenadines', 'short_code' => 'VC', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Samoa', 'short_code' => 'WS', 'currency_code' => 'WST', 'currency_symbol' => 'T', 'currency_position' => $a],
            ['name' => 'San Marino', 'short_code' => 'SM', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Sao Tome and Principe', 'short_code' => 'ST', 'currency_code' => 'STN', 'currency_symbol' => 'Db', 'currency_position' => $a],
            ['name' => 'Saudi Arabia', 'short_code' => 'SA', 'currency_code' => 'SAR', 'currency_symbol' => 'ر.س', 'currency_position' => $a],
            ['name' => 'Senegal', 'short_code' => 'SN', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'currency_position' => $a],
            ['name' => 'Serbia', 'short_code' => 'RS', 'currency_code' => 'RSD', 'currency_symbol' => 'дин.', 'currency_position' => $a],
            ['name' => 'Seychelles', 'short_code' => 'SC', 'currency_code' => 'SCR', 'currency_symbol' => '₨', 'currency_position' => $b],
            ['name' => 'Sierra Leone', 'short_code' => 'SL', 'currency_code' => 'SLE', 'currency_symbol' => 'Le', 'currency_position' => $a],
            ['name' => 'Singapore', 'short_code' => 'SG', 'currency_code' => 'SGD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Slovakia', 'short_code' => 'SK', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Slovenia', 'short_code' => 'SI', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Solomon Islands', 'short_code' => 'SB', 'currency_code' => 'SBD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Somalia', 'short_code' => 'SO', 'currency_code' => 'SOS', 'currency_symbol' => 'Sh', 'currency_position' => $a],
            ['name' => 'South Africa', 'short_code' => 'ZA', 'currency_code' => 'ZAR', 'currency_symbol' => 'R', 'currency_position' => $b],
            ['name' => 'South Korea', 'short_code' => 'KR', 'currency_code' => 'KRW', 'currency_symbol' => '₩', 'currency_position' => $b],
            ['name' => 'South Sudan', 'short_code' => 'SS', 'currency_code' => 'SSP', 'currency_symbol' => '£', 'currency_position' => $b],
            ['name' => 'Spain', 'short_code' => 'ES', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Sri Lanka', 'short_code' => 'LK', 'currency_code' => 'LKR', 'currency_symbol' => '₨', 'currency_position' => $b],
            ['name' => 'Sudan', 'short_code' => 'SD', 'currency_code' => 'SDG', 'currency_symbol' => 'ج.س.', 'currency_position' => $a],
            ['name' => 'Suriname', 'short_code' => 'SR', 'currency_code' => 'SRD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Sweden', 'short_code' => 'SE', 'currency_code' => 'SEK', 'currency_symbol' => 'kr', 'currency_position' => $a],
            ['name' => 'Switzerland', 'short_code' => 'CH', 'currency_code' => 'CHF', 'currency_symbol' => 'CHF', 'currency_position' => $a],
            ['name' => 'Syria', 'short_code' => 'SY', 'currency_code' => 'SYP', 'currency_symbol' => '£', 'currency_position' => $b],
            ['name' => 'Taiwan', 'short_code' => 'TW', 'currency_code' => 'TWD', 'currency_symbol' => 'NT$', 'currency_position' => $b],
            ['name' => 'Tajikistan', 'short_code' => 'TJ', 'currency_code' => 'TJS', 'currency_symbol' => 'ЅМ', 'currency_position' => $a],
            ['name' => 'Tanzania', 'short_code' => 'TZ', 'currency_code' => 'TZS', 'currency_symbol' => 'Sh', 'currency_position' => $a],
            ['name' => 'Thailand', 'short_code' => 'TH', 'currency_code' => 'THB', 'currency_symbol' => '฿', 'currency_position' => $b],
            ['name' => 'Timor-Leste', 'short_code' => 'TL', 'currency_code' => 'USD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Togo', 'short_code' => 'TG', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'currency_position' => $a],
            ['name' => 'Tonga', 'short_code' => 'TO', 'currency_code' => 'TOP', 'currency_symbol' => 'T$', 'currency_position' => $b],
            ['name' => 'Trinidad and Tobago', 'short_code' => 'TT', 'currency_code' => 'TTD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Tunisia', 'short_code' => 'TN', 'currency_code' => 'TND', 'currency_symbol' => 'د.ت', 'currency_position' => $a],
            ['name' => 'Turkey', 'short_code' => 'TR', 'currency_code' => 'TRY', 'currency_symbol' => '₺', 'currency_position' => $b],
            ['name' => 'Turkmenistan', 'short_code' => 'TM', 'currency_code' => 'TMT', 'currency_symbol' => 'm', 'currency_position' => $a],
            ['name' => 'Tuvalu', 'short_code' => 'TV', 'currency_code' => 'AUD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Uganda', 'short_code' => 'UG', 'currency_code' => 'UGX', 'currency_symbol' => 'Sh', 'currency_position' => $a],
            ['name' => 'Ukraine', 'short_code' => 'UA', 'currency_code' => 'UAH', 'currency_symbol' => '₴', 'currency_position' => $a],
            ['name' => 'United Arab Emirates', 'short_code' => 'AE', 'currency_code' => 'AED', 'currency_symbol' => 'د.إ', 'currency_position' => $a],
            ['name' => 'United Kingdom', 'short_code' => 'GB', 'currency_code' => 'GBP', 'currency_symbol' => '£', 'currency_position' => $b],
            ['name' => 'United States', 'short_code' => 'US', 'currency_code' => 'USD', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Uruguay', 'short_code' => 'UY', 'currency_code' => 'UYU', 'currency_symbol' => '$', 'currency_position' => $b],
            ['name' => 'Uzbekistan', 'short_code' => 'UZ', 'currency_code' => 'UZS', 'currency_symbol' => 'so\'m', 'currency_position' => $a],
            ['name' => 'Vanuatu', 'short_code' => 'VU', 'currency_code' => 'VUV', 'currency_symbol' => 'Vt', 'currency_position' => $a],
            ['name' => 'Vatican City', 'short_code' => 'VA', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'currency_position' => $b],
            ['name' => 'Venezuela', 'short_code' => 'VE', 'currency_code' => 'VES', 'currency_symbol' => 'Bs.', 'currency_position' => $b],
            ['name' => 'Vietnam', 'short_code' => 'VN', 'currency_code' => 'VND', 'currency_symbol' => '₫', 'currency_position' => $a],
            ['name' => 'Yemen', 'short_code' => 'YE', 'currency_code' => 'YER', 'currency_symbol' => '﷼', 'currency_position' => $a],
            ['name' => 'Zambia', 'short_code' => 'ZM', 'currency_code' => 'ZMW', 'currency_symbol' => 'ZK', 'currency_position' => $b],
            ['name' => 'Zimbabwe', 'short_code' => 'ZW', 'currency_code' => 'ZWL', 'currency_symbol' => '$', 'currency_position' => $b],
        ];
    }
}
